type product {
  id: ID!,
  title:String,
  price:Int,
  thumbnail:String,
  description:String,
  category:String,
  quantity:Int
}

type order {
  id: ID!,
  products: [product],
  date:String,
  status:String,
  email:String,
  shippingAddress:String,
  total:Int
}

type Query{
  getOrderById(id:ID) : order
}

input userPayload {
  email:String!,
  currentCartId:Int!,
}

type Mutation{
  createNewOrder(user:userPayload) : ID
  deleteOrderById(id:ID) : String
}